"""AKShare 1.18.97 数据源说明；仅供阅读，不参与采集路由或读取配置。

清单中的参数为调用模板，认证值仅占位。业务可用判定是校验规则，
不是实时健康结果；函数数、参数组合数和 HTTP 请求数含义不同。
"""

import json
from typing import Any


# 共用规则只用于说明，实际限频、预算和校验仍由对应 Provider/业务模块执行。
HTTP_RULES = {
    "connectMaxSeconds": 5,
    "readDefaultSeconds": 15,
    "readSetting": "SOURCE_TIMEOUT_SECONDS",
    "shorterLimits": "缺失或 None 补齐上限；已有 scalar/tuple 更短限制保留",
    "retry": "服务不增加即时重试，不并行分页；一次函数调用可能含多个 HTTP 请求",
    "execution": "每次 AKShare 调用独立 spawn；子进程转精简记录，单服务父进程标准化和业务发布",
    "quota": "AUTO：行情/资金两个固定非排队入口；完整market原子取得两个；全局2路、同来源2路；THS/SINA/XQ及蛋卷/SSE/SZSE/BSE",
    "memory": "容器1GiB且无额外swap；cgroup总内存>=800MiB停止准入并回收源进程；RESOURCE不触发源冷却，SIGKILL不直接认定OOM",
    "order": "行情：股票报价→ETF→指数→行业→概念；资金：即时个股全市场榜。跨通道并行，同通道串行/启动至少120秒，完成模块立即发布",
    "lease": "AUTO：令牌租约30秒、每10秒续租；子进程回收后按令牌释放",
    "requestStartGaps": "每次实际HTTP：新浪0.2秒、THS/雪球/交易所1秒、THS基金资料额外2秒",
    "collectionMode": "内部POST先认证X-Internal-Token，再解析X-Collection-Mode；缺省auto，只有auto/manual合法，其它400；CLI/定时/admin沿auto",
    "manual": "manual每请求独立执行器与SourceCall；串行复用同一Provider/标准化/缓存，跳过采集入口/任务锁、普通冷却、任务/代码间隔及源配额；不读取/写入AUTO普通冷却与间隔键",
    "sharedProtection": "两模式共享实际HTTP启动间隔、401/403/429及明确风控risk键；旧冷却原因未知则自然过期，不能推测或清除；源总闸/Token、截止时间、Redis故障、800MiB资源与事务写入保护仍生效",
    "outsideWindow": "manual可休市/窗口外刷新；股票保留真实sourceTime/tradeDate且不得倒退，严格源时间>15:00确认收盘；无可靠源日期的市场/指数/ETF只更新快照与实际collectedAt，不产生日期或曲线点",
    "deadline": "配额等待、模块初始化、HTTP和最多2秒回收均计入原函数/批次预算",
}
THS_MARKET_POLICY = [
    "各通道启动至少120秒；快轮沿原定点节奏，耗时>=120秒的慢轮完成回收后在交易窗口立即接续，不补旧轮",
    "同花顺分页请求至少间隔 1 秒",
    "401/403/429或明确风控拒绝：THS共享源冷却7200秒；普通网络/读取超时/解析/校验失败仅当前模块300秒",
    "SourceDataError：仅失败模块冷却 300 秒；冷却不访问源、不续期、不新增曲线点",
]
PUBLIC_AUTH = "公开网页接口，无服务 Token；仍可能被源站限流或拒绝"
XQ_AUTH = (
    "STOCK_MONITOR_XQ_ENABLED=true 且已配置 XUEQIU_TOKEN 才允许；默认关闭。"
    "只传已授权 Token，不记录 Cookie/Token；一次调用先建立 xueqiu.com 会话"
)
ETF_BUDGET = {
    "processSeconds": "SOURCE_TIMEOUT_SECONDS + 17（默认 32 秒）",
    "cleanupReserveSeconds": 2,
    "profileCap": "资料单次总预算不超过批次剩余预算，超时先终止再回收，行情入口内串行",
}

# 每项对应一种函数参数组合；同一函数的不同业务用途放在 uses 中，不重复计数。
SOURCES: tuple[dict[str, Any], ...] = (
    {
        "id": "calendar-sina", "uses": ["交易日历缓存"],
        "function": "tool_trade_date_hist_sina", "parameters": {},
        "provider": "app.calendar.service.AkShareCalendarSource.dates",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "finance.sina.com.cn",
                       "path": "/realstock/company/klc_td_sh.txt"}],
        "authorization": PUBLIC_AUTH,
        "frequency": ["每月 1 日上海时间 00:10；行情入口启动检查/覆盖不足补建；资金通道只读缓存",
                      "AUTO失败每日限频；AUTO内部按需日历刷新600秒，受独立锁保护；manual绕过两者"],
        "timeout": {"queueWaitSeconds": "SOURCE_TIMEOUT_SECONDS + 10（默认 25 秒）",
                    "normalJoinSeconds": 2, "cleanup": "超时终止并回收子进程"},
        "availability": ["trade_date 每项必须为有效日期；当年有效日期非空",
                         "当年缓存范围须覆盖待判断日期，否则 UNKNOWN，不按工作日推断"],
        "semantics": ["只保留上海时间当年的交易日期，排序去重",
                      "refreshedAt 是缓存刷新时间；失败保留旧缓存，旧年不能用于新年"],
        "entrypoints": ["python -m app calendar-refresh", "/internal/jobs/v1/calendar/refresh"],
    },
    {
        "id": "industry-ths", "uses": ["行业板块行情与资金流（热力图/涨跌Top10/资金Top10同批复用）"],
        "function": "stock_fund_flow_industry", "parameters": {"symbol": "即时"},
        "provider": "app.providers.akshare_market.AkShareMarketProvider.sector_fund_flow(industry)",
        "endpoints": [{"method": "GET", "scheme": "http", "domain": "data.10jqka.com.cn",
                       "path": "/funds/hyzjl/field/tradezdf/order/desc/ajax/1/free/1/"},
                      {"method": "GET", "scheme": "http", "domain": "data.10jqka.com.cn",
                       "path": "/funds/hyzjl/field/tradezdf/order/desc/page/{page}/ajax/1/free/1/"}],
        "authorization": PUBLIC_AUTH, "frequency": THS_MARKET_POLICY,
        "timeout": {"functionBudgetSeconds": 120},
        "availability": ["必需列：行业、行业指数、行业-涨跌幅、流入资金、流出资金、净额",
                         "过滤无名称、名称重复或所有关键值无效的行；至少一条有效板块"],
        "semantics": ["板块纯数值金额按亿元转换成元；显式单位优先",
                      "涨跌幅/净流率为百分数，净流率=净额/(流入+流出)*100",
                      "无可靠源日期/逐条源时间；tradeDate 来自日历，collectedAt 是采集时间"],
        "entrypoints": ["python -m app collect", "/internal/jobs/v1/market/refresh"],
    },
    {
        "id": "concept-ths", "uses": ["概念板块行情与资金流（热力图/涨跌Top10/资金Top10同批复用）"],
        "function": "stock_fund_flow_concept", "parameters": {"symbol": "即时"},
        "provider": "app.providers.akshare_market.AkShareMarketProvider.sector_fund_flow(concept)",
        "endpoints": [{"method": "GET", "scheme": "http", "domain": "data.10jqka.com.cn",
                       "path": "/funds/gnzjl/field/tradezdf/order/desc/ajax/1/free/1/"},
                      {"method": "GET", "scheme": "http", "domain": "data.10jqka.com.cn",
                       "path": "/funds/gnzjl/field/tradezdf/order/desc/page/{page}/ajax/1/free/1/"}],
        "authorization": PUBLIC_AUTH, "frequency": THS_MARKET_POLICY,
        "timeout": {"functionBudgetSeconds": 120},
        "availability": ["输出列沿用行业字段名；使用行业板块相同的标准化规则，至少一条有效概念"],
        "semantics": ["纯数值资金为亿元，落契约为元；显式单位优先，涨跌幅为百分数",
                      "无可靠源时间；交易日期来自日历，采集时间不能作为源交易时间"],
        "entrypoints": ["python -m app collect", "/internal/jobs/v1/market/refresh"],
    },
    {
        "id": "individual-ths", "uses": ["全市场资金汇总", "已启用个股资金曲线（共用同一批次）"],
        "function": "stock_fund_flow_individual", "parameters": {"symbol": "即时"},
        "provider": "app.providers.akshare_market.AkShareMarketProvider.market_fund_flow",
        "endpoints": [{"method": "GET", "scheme": "http", "domain": "data.10jqka.com.cn",
                       "path": "/funds/ggzjl/field/code/order/desc/ajax/1/free/1/"},
                      {"method": "GET", "scheme": "http", "domain": "data.10jqka.com.cn",
                       "path": "/funds/ggzjl/field/code/order/desc/page/{page}/ajax/1/free/1/"}],
        "authorization": PUBLIC_AUTH, "frequency": THS_MARKET_POLICY,
        "timeout": {"functionBudgetSeconds": 900},
        "availability": ["六位股票代码及名称有效，涨跌幅/流入/流出必需有效；重复有效行不得冲突",
                         "关键值缺失或冲突整批拒绝；页码/总页数/原始行数审计，代码严格倒序且全批无重复；源净额可缺失，只对有效源净额的同一子集审计"],
        "semantics": ["个股纯数值资金为元；显式元/万/亿转换为元",
                      "市场及个股 netAmount 均为同批流入减流出；涨跌计数来自同批去重股票",
                      "只改即时个股准确域名与zdf分页路径为code；保留原AKShare解析，排序不支持则失败；行业/概念及非即时参数不改",
                      "日历日期与实际采集时间；不为个股资金新增逐股源调用"],
        "entrypoints": ["python -m app collect", "/internal/jobs/v1/market/refresh"],
    },
    {
        "id": "indices-sina", "uses": ["五只核心指数行情与曲线"],
        "function": "stock_zh_index_spot_sina", "parameters": {},
        "provider": "app.providers.akshare_market.AkShareMarketProvider.index_spot",
        "endpoints": [{"method": "GET", "scheme": "http", "domain": "vip.stock.finance.sina.com.cn",
                       "path": "/quotes_service/api/json_v2.php/Market_Center.getHQNodeStockCountSimple",
                       "query": {"node": "hs_s"}},
                      {"method": "GET", "scheme": "http", "domain": "vip.stock.finance.sina.com.cn",
                       "path": "/quotes_service/api/json_v2.php/Market_Center.getHQNodeDataSimple",
                       "query": {"page": "{page}", "num": "80", "sort": "symbol", "asc": "1",
                                 "node": "hs_s", "_s_r_a": "page"}}],
        "authorization": PUBLIC_AUTH,
        "frequency": ["行情 120 秒；源请求至少间隔 0.2 秒",
                      "401/403/429或明确风控拒绝：sina-index源7200秒；普通网络/读取超时/解析/校验失败只暂停当前模块300秒"],
        "timeout": {"functionBudgetSeconds": 120},
        "availability": ["sh000001、sz399001、sh000300、sz399006、sh000688 必须全部存在",
                         "各点位有效且>0、重复行无冲突；缺任一则模块降级"],
        "semantics": ["价格为指数点位，涨跌幅为百分数；量额沿用接口数值，不当作个股资金",
                      "sourceTime=null；曲线记录实际采集时间，不推断实时或收盘确认"],
        "entrypoints": ["python -m app collect", "/internal/jobs/v1/market/refresh"],
    },
    {
        "id": "dictionary-sh-main", "uses": ["上海主板 A 股字典"],
        "function": "stock_info_sh_name_code", "parameters": {"symbol": "主板A股"},
        "provider": "app.providers.exchange_stocks.ExchangeStockProvider.all_a_stocks",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "query.sse.com.cn",
                       "path": "/sseQuery/commonQuery.do", "query": {"STOCK_TYPE": "1",
                       "sqlId": "COMMON_SSE_CP_GPJCTPZ_GPLB_GP_L", "pageHelp.pageSize": "10000"},
                       "headers": {"Referer": "https://www.sse.com.cn/assortment/stock/list/share/"}}],
        "authorization": PUBLIC_AUTH,
        "frequency": ["Python按需入口；Java工作日16:30整体刷新/手动刷新；字典四种组合串行，全部校验后合并；每次HTTP>=1秒，清理AKShare缓存"],
        "timeout": {"functionBudgetSeconds": 60, "note": "包含准入等待与回收，每次HTTP仍有上限"},
        "availability": ["本组合非空，证券代码/证券简称有效；六位代码；合并重复无冲突且三市场均有股票"],
        "semantics": ["市场 SH；字典股票名称不是行情；上市日期来自交易所字段，但当前统一字典只保留基础四字段"],
        "entrypoints": ["/internal/stock-monitor/v1/exchange-dictionary"],
    },
    {
        "id": "dictionary-sh-star", "uses": ["上海科创板字典"],
        "function": "stock_info_sh_name_code", "parameters": {"symbol": "科创板"},
        "provider": "app.providers.exchange_stocks.ExchangeStockProvider.all_a_stocks",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "query.sse.com.cn",
                       "path": "/sseQuery/commonQuery.do", "query": {"STOCK_TYPE": "8",
                       "sqlId": "COMMON_SSE_CP_GPJCTPZ_GPLB_GP_L", "pageHelp.pageSize": "10000"},
                       "headers": {"Referer": "https://www.sse.com.cn/assortment/stock/list/share/"}}],
        "authorization": PUBLIC_AUTH,
        "frequency": ["与主板、深圳、北京字典同批串行，同一字典任务串行，全局SSE配额最多2路，清理缓存"],
        "timeout": {"functionBudgetSeconds": 60},
        "availability": ["本组合非空，证券代码/证券简称有效；六位代码；合并重复无冲突且三市场均有股票"],
        "semantics": ["市场仍为 SH；symbol=科创板是另一参数组合，不是另一唯一函数"],
        "entrypoints": ["/internal/stock-monitor/v1/exchange-dictionary"],
    },
    {
        "id": "dictionary-sz", "uses": ["深圳 A 股字典"],
        "function": "stock_info_sz_name_code", "parameters": {"symbol": "A股列表"},
        "provider": "app.providers.exchange_stocks.ExchangeStockProvider.all_a_stocks",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "www.szse.cn",
                       "path": "/api/report/ShowReport",
                       "query": {"SHOWTYPE": "xlsx", "CATALOGID": "1110", "TABKEY": "tab1"}}],
        "authorization": PUBLIC_AUTH,
        "frequency": ["四组字典串行，SZSE每次HTTP>=1秒，清理函数缓存"],
        "timeout": {"functionBudgetSeconds": 60, "note": "AKShare read=15 更短时保留"},
        "availability": ["非空 Excel；A股代码/A股简称有效；六位代码；合并无冲突且三市场均有股票"],
        "semantics": ["市场 SZ；名单源 XLSX 与统一字典 JSON 是不同结构"],
        "entrypoints": ["/internal/stock-monitor/v1/exchange-dictionary"],
    },
    {
        "id": "dictionary-bj", "uses": ["北京股票字典"],
        "function": "stock_info_bj_name_code", "parameters": {},
        "provider": "app.providers.exchange_stocks.ExchangeStockProvider.all_a_stocks",
        "endpoints": [{"method": "POST", "scheme": "https", "domain": "www.bse.cn",
                       "path": "/nqxxController/nqxxCnzq.do", "form": {"page": "{page，从0开始}",
                       "typejb": "T", "xxfcbj[]": "2", "sortfield": "xxzqdm", "sorttype": "asc"}}],
        "authorization": PUBLIC_AUTH,
        "frequency": ["函数先读取页数再串行 POST 分页；清理缓存，BSE每次HTTP>=1秒"],
        "timeout": {"functionBudgetSeconds": 60},
        "availability": ["非空；证券代码/证券简称有效；六位代码；合并无冲突且三市场均有股票"],
        "semantics": ["市场 BJ；一次函数调用含多个 POST，不以首页成功代表全字典有效"],
        "entrypoints": ["/internal/stock-monitor/v1/exchange-dictionary"],
    },
    {
        "id": "stock-profile-xq", "uses": ["个股行业、上市日期资料"],
        "function": "stock_individual_basic_info_xq",
        "parameters": {"symbol": "{SH|SZ|BJ+六位代码}", "token": "{已授权Token，仅占位}",
                       "timeout": "(5, SOURCE_TIMEOUT_SECONDS)"},
        "provider": "app.providers.xueqiu.XueqiuProvider.profile",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "xueqiu.com", "path": "/"},
                      {"method": "GET", "scheme": "https", "domain": "stock.xueqiu.com",
                       "path": "/v5/stock/f10/cn/company.json", "query": {"symbol": "{symbol}"}}],
        "authorization": XQ_AUTH,
        "frequency": ["Python按需；Java工作日16:30整体刷新/手动资料刷新；资料最多10只、跨股票串行，资料仍查原源；仅缺市值时复用同代码XQ/FRESH且120秒内报价的市值，同股补报价受120秒间隔保护；每次实际HTTP>=1秒",
                      "与报价共享股票采集锁；认证拒绝/限流触发现有雪球 7200 秒冷却"],
        "timeout": {"functionBudgetSeconds": 300, "batchBudgetSeconds": 600, "note": "会话及数据请求均受共享速率与HTTP超时约束"},
        "availability": ["非空 item/value 表；股票代码有效；可空字段不得填造"],
        "semantics": ["行业来自 affiliate_industry.ind_name；上市日期来自 listed_date",
                      "updatedAt 是资料更新时刻，不是源交易时间；市值可由额外报价补充，单位元"],
        "entrypoints": ["/internal/stock-monitor/v1/profiles"],
    },
    {
        "id": "stock-quote-xq", "uses": ["个股行情及价格曲线", "个股资料市值补充"],
        "function": "stock_individual_spot_xq",
        "parameters": {"symbol": "{SH|SZ|BJ+六位代码}", "token": "{已授权Token，仅占位}",
                       "timeout": "(5, SOURCE_TIMEOUT_SECONDS)"},
        "provider": "app.providers.xueqiu.XueqiuProvider.quote",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "xueqiu.com", "path": "/"},
                      {"method": "GET", "scheme": "https", "domain": "stock.xueqiu.com",
                       "path": "/v5/stock/quote.json", "query": {"symbol": "{symbol}", "extend": "detail"}}],
        "authorization": XQ_AUTH,
        "frequency": ["盘中每120秒，同股请求TTL=120秒，跨股票串行，每次实际HTTP启动间隔>=1秒",
                      "15:02/04/06/08/10 补收盘确认；已确认跳过；拒绝/限流现有冷却7200秒"],
        "timeout": {"functionBudgetSeconds": 300, "batchBudgetSeconds": 300, "note": "建会话和取数据均取得HTTP速率许可"},
        "availability": ["非空 item/value；有效源时间，现价/涨幅/成交额至少一项有效",
                         "历史有效不等于当前实时；未来日期、旧日期、倒退/不变源时间按业务拒绝或降级"],
        "semantics": ["AKShare 将毫秒时间戳转无时区字符串，Provider 设上海时区",
                      "价格元、涨幅百分数、成交额/市值元；曲线用 sourceTime，不用采集时间",
                      "同日源时间严格晚于15:00才可确认收盘；可空字段不补造"],
        "entrypoints": ["python -m app monitor-sample", "/internal/jobs/v1/monitor/refresh",
                        "/internal/stock-monitor/v1/profiles"],
    },
    {
        "id": "etf-sina", "uses": ["ETF 字典", "ETF 交易报价与价格曲线（共用函数及参数）"],
        "function": "fund_etf_category_sina", "parameters": {"symbol": "ETF基金"},
        "provider": "app.providers.akshare_etf.AkShareEtfProvider.quotes",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "vip.stock.finance.sina.com.cn",
                       "path": "/quotes_service/api/jsonp.php/IO.XSRV2.CallbackList['da_yPT46_Ll7K6WD']/Market_Center.getHQNodeDataSimple",
                       "query": {"page": "1", "num": "5000", "sort": "symbol", "asc": "0",
                                 "node": "etf_hq_fund", "[object HTMLDivElement]": "qvvne"}}],
        "authorization": PUBLIC_AUTH + "；不受雪球总闸控制",
        "frequency": ["行情120秒；字典Python按需优先当日缓存，Java工作日16:40整体刷新/手动刷新；SINA组跨入口每次实际HTTP间隔>=0.2秒；固定版当前一次GET(page=1,num=5000)",
                      "ETF行情403/429冷却7200秒，普通网络/超时/格式/标准化错误300秒",
                      "冷却只记录INFO及TTL，不调用源、不续期、不新增价格点；字典路由不走行情普通冷却；两模式仍服从共享新浪风控"],
        "timeout": ETF_BUDGET,
        "availability": ["字典：有效sh/sz六位代码及名称，至少一只ETF",
                         "报价：有效代码和>0交易价格，重复无冲突；至少一条有效报价，缺监控代码降级"],
        "semantics": ["最新价为交易价（元），不是基金净值；涨幅百分数、成交额沿接口数值",
                      "无可靠源时间，sourceTime=null；collectedAt是实际采集完成时间，不能推断收盘",
                      "同一新浪全表同时生成启用ETF行情与dictionary-source轻量全量字典，TTL86400；AUTO字典接口优先合法上海当日缓存；MANUAL字典强制一次新浪全表请求并更新缓存，失败保留旧缓存",
                      "无可靠ETF资金流：fundSeries空，fundFlowStatus=NO_RELIABLE_SOURCE；资产配置状态由Java按MySQL报告与总闸生成"],
        "entrypoints": ["python -m app etf-collect", "/internal/jobs/v1/etf/refresh",
                        "/internal/etf-monitor/v1/dictionary"],
    },
    {
        "id": "etf-profile-ths", "uses": ["ETF 基本资料"],
        "function": "fund_info_ths", "parameters": {"symbol": "{六位基金代码}"},
        "provider": "app.providers.akshare_etf.AkShareEtfProvider.profile",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "fund.10jqka.com.cn",
                       "path": "/{symbol}/interduce.html"}],
        "authorization": PUBLIC_AUTH + "；不受雪球总闸控制；禁用重定向，限制实际请求域名",
        "frequency": ["AUTO按需；Java工作日16:40整体刷新；manual资料刷新绕过批次锁及1800秒间隔但每次HTTP仍>=2秒；逐代码1800秒限频，批次最多10只、串行1路、180秒预算，请求间隔>=2秒",
                      "独立Python批次锁210秒；失败也受已有30分钟资料限频保护"],
        "timeout": ETF_BUDGET,
        "availability": ["字段/值表非空且字段不冲突；基金代码必须匹配请求六位代码",
                         "全称/基金类型/投资类型/经理/成立日期/业绩基准/管理人/托管人至少一项有效"],
        "semantics": ["成立日期不是上市日期；基金经理不是基金管理人",
                      "业绩基准不推导跟踪指数；collectedAt是资料采集时间"],
        "entrypoints": ["/internal/etf-monitor/v1/profiles"],
    },
    {
        "id": "etf-allocation-xq", "uses": ["ETF 基金资产配置类别占比"],
        "function": "fund_individual_detail_hold_xq",
        "parameters": {"symbol": "{六位基金代码}", "date": "{YYYYMMDD}",
                       "timeout": "SOURCE_TIMEOUT_SECONDS"},
        "provider": "app.providers.akshare_etf.AkShareEtfProvider.asset_allocation",
        "endpoints": [{"method": "GET", "scheme": "https", "domain": "danjuanfunds.com",
                       "path": "/djapi/fundx/base/fund/record/asset/percent",
                       "query": {"fund_code": "{symbol}", "report_date": "{YYYY-MM-DD，由date转换}"}}],
        "authorization": "服务要求雪球总闸开启且已配置Token；该AKShare函数没有token形参，不会传Token给它",
        "frequency": ["独立内部接口，占用一个共享XQ名额，每次HTTP>=1秒，不属于八个scheduler固定刷新入口",
                      "不使用ETF行情冷却键；不为其新增探测限频或重试"],
        "timeout": ETF_BUDGET,
        "availability": ["至少一个有效资产类型及有限仓位占比，0<=percent<=100"],
        "semantics": ["资产类型/仓位占比（百分数），不是成分股持仓",
                      "requestedReportPeriod仅为请求报告期，不代表真实披露时间；不补造源披露日"],
        "entrypoints": ["/internal/etf-monitor/v1/asset-allocation"],
    },
)


def render_sources(*, as_json: bool = False) -> str:
    """只序列化静态说明；不导入配置、Provider、Redis 或网络库。"""
    payload = {
        "schemaVersion": 1, "akshareVersion": "1.18.97",
        "verificationStatus": "NOT_CHECKED",
        "notice": "仅为接口说明，本命令不发起真实请求，不证明任何源当前健康",
        "uniqueFunctionCount": len({source["function"] for source in SOURCES}),
        "parameterCombinationCount": len(SOURCES),
        "httpRules": HTTP_RULES, "sources": SOURCES,
    }
    if as_json:
        return json.dumps(payload, ensure_ascii=False, indent=2)
    lines = [f"AKShare {payload['akshareVersion']}：{payload['uniqueFunctionCount']} 个唯一函数，"
             f"{payload['parameterCombinationCount']} 种参数调用组合", payload["notice"]]
    for source in SOURCES:
        parameters = ", ".join(f"{name}={value!r}" for name, value in source["parameters"].items())
        domains = ", ".join(dict.fromkeys(endpoint["domain"] for endpoint in source["endpoints"]))
        lines.append(f"\n[{source['id']}] {'；'.join(source['uses'])}\n"
                     f"  akshare.{source['function']}({parameters})\n  域名：{domains}")
    lines.append("\n完整参数/路径/授权/频率/超时/字段语义：python -m app sources --json\n"
                 "仓库手动验证说明：docs/source-health-check.md")
    return "\n".join(lines)
